name: C CI

on:
  push:
  pull_request:

env:
  parallelism: -j8

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: dependencies
      run: |
        : Install Dependencies
        sudo apt-get update
        sudo apt-get install -y gettext
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make $parallelism
    - name: make check
      run: make check $parallelism
    - name: make distcheck
      run: make distcheck $parallelism
